global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Frontend Application
  - job_name: 'frontend-app'
    static_configs:
      - targets: ['frontend:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: false
    scheme: http

  # Backend Application  
  - job_name: 'backend-app'
    static_configs:
      - targets: ['backend:5001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: false
    scheme: http

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s